### ISSUE TITLE
여행지 탐색

### ISSUE THREAD

**Issue by hyo814** [TripTune-Project/TripTune-Frontend#86]
- [ ]  파일 분리
- [ ]  여행지 탐색
    - [x]  페이지 렌더링 되기 전에 값이 없어서 로그인이  간헐적으로 풀려보이는 이슈
    - [x]  "DB에 저장된 refresh token과 일치하지 않습니다. 다시 로그인해주세요." 이 경우에 대한 대처 필요
    - [x]  list api 가 두번 조회 되는 현상 "여행지 탐색 기본/ 검색 "
    - [x]  GetViewportInfo가 두번 조회되는 현상 "여행지 탐색 기본/ 검색 "
    - [x]  디바운스로 자동 검색 중인데 지금 보니까 0.5초 ~ 1초 뒤에 포커스 사라져도 괜찮은지 고민
    - [x]  home 진행 시 api 변수명 확인 할 것
    - [x]  검색 결과 기록이 남아 있는 경우가 있음
    - [x]  사용자 권한 허용을 크롬에서 강제로 끄고 켜야 권한 알람이 뜨는 거도 확인 해야함
    - [x]  여행지 탐색 상세 페이지 api 확인 및 수정
    - [x] 여행지 탐색 상세 페이지에도 지도가 있는게 나을지?
    - [x] 지도의 마커나 로드가 간헐적으로 깨지는 이슈
- [ ]  **화살표 표시** 알아보기 :  로그인
- [x]  반응형
- [x]  라이트 하우스 개선

**Comment by soyamilk0705** [comment]
혹시 백엔드에서 수정해야할거나 확인했으면 하는 부분 있어?

**Comment by hyo814** [comment]
기본 지도와 마커 설정의 차이: 기본 지도 설정과 마커나 기타 오버레이 설정이 각각 별도의 요청을 발생시키는 경우가 있습니다. 예를 들어, 기본 지도에 대한 초기 요청 후에 추가적인 마커나 커스텀 데이터를 로드하기 위해 두 번째 요청이 발생할 수 있습니다.
